version: '3.8'

services:
  app:
    build: .
    container_name: tg_poster_app
    restart: always
    volumes:
      - ./media:/app/media
      - ./.env:/app/.env
    depends_on:
      - db
    networks:
      tg_poster_network:
        ipv4_address: 172.20.0.3
    # Удаляем публикацию порта API
    # ports:
    #   - "8002:8002"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/tg_poster
      - API_HOST=0.0.0.0
      - API_PORT=8002

  db:
    image: postgres:14-alpine
    container_name: tg_poster_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tg_poster
    networks:
      tg_poster_network:
        ipv4_address: 172.20.0.2
    # Порт базы данных больше не публикуется наружу
    # ports:
    #   - "5432:5432"

  nginx:
    image: nginx:alpine
    container_name: tg_poster_nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./media:/app/media
    depends_on:
      - app
    networks:
      tg_poster_network:
        ipv4_address: 172.20.0.4
    # Удаляем публикацию порта веб-интерфейса
    # ports:
    #   - "8080:80"

networks:
  tg_poster_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  postgres_data:
